# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
    services:
      mssqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Secret123
    steps:
    - uses: actions/checkout@v2
    - run: docker ps
    - run: sleep 5
    - run: docker exec ${{ job.services.mssqlserver.id }} /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Secret123 -Q "create database test;"
    - run: python test_minitds.py
